"""initial migration

Revision ID: 0d18abb9921c
Revises: 
Create Date: 2025-01-29 19:20:57.899297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0d18abb9921c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_keys')
    with op.batch_alter_table('favorite_gpus', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'gpu_listings', ['gpu_id'], ['id'])

    with op.batch_alter_table('price_alerts', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'gpu_listings', ['gpu_id'], ['id'])

    with op.batch_alter_table('rented_gpus', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'gpu_listings', ['gpu_id'], ['id'])

    with op.batch_alter_table('selected_gpus', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'gpu_listings', ['gpu_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('selected_gpus', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('rented_gpus', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('price_alerts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('favorite_gpus', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('api_keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('permission', postgresql.ENUM('read', 'admin', name='api_key_permission'), server_default=sa.text("'read'::api_key_permission"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='api_keys_pkey'),
    sa.UniqueConstraint('key', name='api_keys_key_key')
    )
    # ### end Alembic commands ###
