"""Update GPU schema for gpuhunt integration

Revision ID: 1c11b26cc472
Revises: 
Create Date: 2025-01-14 21:22:58.101309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c11b26cc472'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gpu_listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instance_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('gpu_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('gpu_vendor', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gpu_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('gpu_memory', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cpu', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('memory', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('disk_size', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=False))
        batch_op.drop_column('price_metric')
        batch_op.drop_column('description')
        batch_op.drop_column('flops')
        batch_op.drop_column('number_of_gpus')
        batch_op.drop_column('vram')
        batch_op.drop_column('image_url')
        batch_op.drop_column('name')
        batch_op.drop_column('reliability')

    with op.batch_alter_table('gpu_price_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('spot', sa.Boolean(), nullable=True))
        batch_op.drop_column('region')
        batch_op.drop_column('cpu_count')
        batch_op.drop_column('memory_gb')
        batch_op.drop_column('provider')
        batch_op.drop_column('spot_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gpu_price_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spot_price', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('provider', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('memory_gb', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cpu_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('region', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('spot')
        batch_op.drop_column('location')

    with op.batch_alter_table('gpu_listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reliability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('vram', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('number_of_gpus', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('flops', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('price_metric', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_column('last_updated')
        batch_op.drop_column('disk_size')
        batch_op.drop_column('memory')
        batch_op.drop_column('cpu')
        batch_op.drop_column('gpu_memory')
        batch_op.drop_column('gpu_count')
        batch_op.drop_column('gpu_vendor')
        batch_op.drop_column('gpu_name')
        batch_op.drop_column('instance_name')

    # ### end Alembic commands ###
